version: 0.2
phases:
  install:
    runtime-versions:
      python: 3.10
  build:
    commands:
      - aws cloudformation package --template-file search-function.yaml --s3-bucket artifacts-bucket-gl-esanchez --output-template-file function.yaml

artifacts:
  type: zip
  files:
    - search-function.yaml
    - function.yaml